### ISSUE TITLE
問題文の長さによってVenueが見切れる

### ISSUE THREAD

**Issue by kazzool** [240webapp/quizzool#55]
- [x] Venueの問題文の改行について検討
→ #48 の事象の一部のため、併せてクローズ
- [x] アス比16:9対応
- [x] Answerモード：回答選択肢改行対応（全角12文字）
- [ ] Rankingモード：名前文字数対応（所属:全角5＋区切り文字:全角1＋名前: 全角6＝全角12文字）

**Comment by albasimia** [comment]
これってスマホ表示の話ですか？

**Comment by kazzool** [comment]
@albasimia 
pcフルスクリーンの話です。
もしやと思って環境毎に確認したところ差異があったので、
どうやら#48と同じ原因で起きていたみたいです。

【本番】
<img width="1280" alt="スクリーンショット 2019-06-15 21 20 40" src="https://user-images.githubusercontent.com/36259171/59551390-c0519200-8fb3-11e9-95b3-acf302513f8b.png">

【ローカル】
<img width="1280" alt="スクリーンショット 2019-06-15 21 25 45" src="https://user-images.githubusercontent.com/36259171/59551421-2a6a3700-8fb4-11e9-9c76-36319a042cf5.png">

**Comment by albasimia** [comment]
#48 
これと一緒。

**Comment by kazzool** [comment]
こっちはクローズで問題ナシの方針で

**Comment by kazzool** [comment]
# 悲しみのリオープン
- 16:9対応してください。。。

**Comment by albasimia** [comment]
残: 縦長のディスプレイ対応。
